version: 2
mergeable:
  - when: issues.opened, issues.reopened
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: description
                must_include:
                  regex: '### PHP Version'
              - do: description
                must_include:
                  regex: '### CodeIgniter Version'
          - do: author
            must_include:
              regex: ^kenjis|lonnieezell|MGatner|michalsn|samsonasik$
    fail:
      - do: comment
        payload:
          body: |
            Hi there, @@author! :wave:

            It looks like you opened an issue without following the bug report template:

            * Bug report ([open an issue](https://github.com/codeigniter4/CodeIgniter4/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Bug%3A+))
            * For feature request or support question, please use the [forums](https://forum.codeigniter.com/forum-30.html).

            The current issue will be closed. This is a precaution to save maintainers' time, I hope you'll understand.

            Sincerely, the mergeable bot 🤖
      - do: close
  
  - when: pull_request.opened, pull_request.ready_for_review
    filter:
      - do: payload
        pull_request:
          author_association:
            must_include:
              regex: ^NONE|FIRST_TIMER|FIRST_TIME_CONTRIBUTOR$
    validate: []
    pass:
      - do: comment
        payload:
          body: |
            Hi there, @@author! :wave:

            Thanks for your contribution! :tada:

            I see you are a first-time contributor. Welcome to the CodeIgniter community! :heart:

            I'll assign a maintainer to review your pull request. Please be patient, they will get back to you soon.

            Sincerely, the mergeable bot 🤖
