name: Carson

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

jobs:
  carson:
    runs-on: ubuntu-latest
    steps:
      - uses: NexusPHP/carson@84d29861578717e439d20e705ed02b7e915b6e07
        with:
          app_id: ${{ secrets.CARSON_APP_ID }}
          private_key: ${{ secrets.CARSON_PRIVATE_KEY }}
          log_level: info
